language: node_js

node_js:
- node

script: gulp build

cache:
  directories:
    - "node_modules"

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
  email: developer@acaprojects.com
  name: SG Doc Bot
