site_name: Spider Gazelle
use_directory_urls: true
repo_url: https://github.com/spider-gazelle
edit_uri: https://github.com/spider-gazelle/guide
site_url: https://spider-gazelle.net

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light theme
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  favicon: favicon.ico
  logo: img/logo.png

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          crystal_docs_flags:
            - lib/action-controller/src/action-controller.cr
          source_locations:
            lib/action-controller: https://github.com/spider-gazelle/action-controller/blob/v{shard_version}/{file}#L{line}

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - deduplicate-toc
  - toc:
      permalink: "#"

extra:
  # analytics:
  #  provider: google
  #  property: UA-184169799-1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spider-gazelle
